version: "3.5"

services:
  builder:
    build:
      context: .
      dockerfile: ./builder/Dockerfile
    image: ghcr.io/paullockaby/lmnop/builder
    container_name: builder
    networks:
      - lmnop
    ports:
      - 8000:80/tcp
    environment:
      - LMNOP_DEPLOY_BRANCH=main
      - LMNOP_HOMEPAGE_URL=http://localhost:8000
      - LMNOP_FUNCTION_URL=http://localhost:8000/function/[]
      - LMNOP_GATEWAY=http://host.docker.internal:30001
      - LMNOP_REGISTRY=host.docker.internal:30002/lmnop
      - LMNOP_DATABASE_HOST=db
      - LMNOP_DATABASE_PORT=5432
      - LMNOP_DATABASE_NAME=lmnop
      - LMNOP_DATABASE_USERNAME=postgres
      - LMNOP_DATABASE_PASSWORD=postgres
      - DOCKER_HOST=tcp://dind:2375
      - HTTPD_PROXY_PROTOCOL=Off
      - HTTPD_LOG_SERVER=localhost
      - HTTPD_SERVER_NAME=localhost:8000
  router:
    build:
      context: .
      dockerfile: ./router/Dockerfile
    image: ghcr.io/paullockaby/lmnop/router
    container_name: router
    networks:
      - lmnop
    ports:
      - 3000:80/tcp
    environment:
      - LMNOP_GATEWAY=http://host.docker.internal:30001
      - HTTPD_PROXY_PROTOCOL=Off
      - HTTPD_LOG_SERVER=localhost
      - HTTPD_SERVER_NAME=localhost:3000
  portal:
    build:
      context: .
      dockerfile: ./portal/Dockerfile
    image: ghcr.io/paullockaby/lmnop/portal
    entrypoint:
      - /entrypoints/run
      - --chdir=/home/lmnop/app/src
      - --bind=0.0.0.0:8080
      - --worker-class=gevent
      - --log-config=configurations/logging.conf
    container_name: portal
    networks:
      - lmnop
    ports:
      - 8080:8080/tcp
    environment:
      - LMNOP_HOMEPAGE_URL=http://localhost:8000
      - LMNOP_FUNCTION_URL=http://localhost:8000/function/[]
      - LMNOP_GATEWAY=http://host.docker.internal:30001
      - LMNOP_DATABASE_HOST=db
      - LMNOP_DATABASE_PORT=5432
      - LMNOP_DATABASE_NAME=lmnop
      - LMNOP_DATABASE_USERNAME=postgres
      - LMNOP_DATABASE_PASSWORD=postgres
  dind:
    image: docker.io/library/docker:20.10.10-dind
    command:
      - dockerd
      - --storage-driver=overlay2
      - --insecure-registry=host.docker.internal:30002
      - --host=tcp://0.0.0.0:2375
      - --tls=false
    container_name: dind
    privileged: true
    networks:
      - lmnop
  postgres:
    image: docker.io/library/postgres:13
    container_name: db
    networks:
      - lmnop
    ports:
      - 5432:5432/tcp
    volumes:
      - ./sql/schema:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lmnop

networks:
  lmnop:
    driver: bridge
    name: lmnop
