---
# Source: openfaas/templates/gateway-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    component: gateway
    release: openfaas
  name: gateway
  namespace: "openfaas"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: gateway
