CREATE TRIGGER t40_distinct BEFORE UPDATE ON lmnop.authn FOR EACH ROW EXECUTE PROCEDURE standard.distinct();
CREATE TRIGGER t40_distinct BEFORE UPDATE ON lmnop.project FOR EACH ROW EXECUTE PROCEDURE standard.distinct();

CREATE TRIGGER t50_updated BEFORE INSERT OR UPDATE ON lmnop.authn FOR EACH ROW EXECUTE PROCEDURE standard.updated();
CREATE TRIGGER t50_updated BEFORE INSERT OR UPDATE ON lmnop.project FOR EACH ROW EXECUTE PROCEDURE standard.updated();

CREATE TRIGGER t90_history AFTER INSERT OR UPDATE OR DELETE ON lmnop.authn FOR EACH ROW EXECUTE PROCEDURE standard.history();
CREATE TRIGGER t90_history AFTER INSERT OR UPDATE OR DELETE ON lmnop.project FOR EACH ROW EXECUTE PROCEDURE standard.history();
